module.exports.JobList = {
    pay: {
        None: 0,
        begger: 250,
        janitor: 1500,
        cashier: 2000,
        bartender: 3000,
        server: 4500,
        assistant: 6000,
        teacher: 7500,
        mechanic: 9000,
        nurse: 12500,
        accountant: 17500,
        techsupport: 20000,
        softwaredeveloper: 27500,
        lawyer: 35000,
        politician: 40000
    },
    workReq: {
        None: 0,
        begger: 0,
        janitor: 0,
        cashier: 15,
        bartender: 35,
        server: 80,
        assistant: 170,
        teacher: 290,
        mechanic: 500,
        nurse: 900,
        accountant: 1400,
        techsupport: 2500,
        softwaredeveloper: 3200,
        lawyer: 5000,
        politician: 7500
    },
    formatName: {
        None: "None",
        begger: "Begger",
        janitor: "Janitor",
        cashier: "Cashier",
        bartender: "Bartender",
        server: "Server",
        assistant: "Assistant",
        teacher: "Teacher",
        mechanic: "Mechanic",
        nurse: "Nurse",
        accountant: "Accountant",
        techsupport: "Tech Support",
        softwaredeveloper: "Software Developer",
        lawyer: "Lawyer",
        politician: "Politician"
    }
}