module.exports.UnscrambleWords = [
    "Economy", 
    "Stocks", 
    "Money", 
    "Cash", 
    "Work", 
    "Gamer", 
    "Janitor",
    "Rich",
    "Discord",
    "Time",
    "Life",
    "Company",
    "Profit",
];